import type { MetaFunction } from "react-router";

export const meta: MetaFunction = () => [{ title: "Terms of Service — RAG AI Agent" }];

const SECTION_STYLE = { marginBottom: "1.5rem" };

/** Public, unauthenticated page — linked from the Shopify App Store listing. */
export default function Terms() {
  return (
    <main style={{ maxWidth: "720px", margin: "0 auto", padding: "3rem 1.5rem", lineHeight: 1.6, fontFamily: "sans-serif" }}>
      <h1>Terms of Service</h1>
      <p style={{ color: "#666" }}>Last updated: August 26, 2026</p>

      <section style={SECTION_STYLE}>
        <h2>The service</h2>
        <p>
          RAG AI Agent (&quot;the app&quot;) is an AI assistant embedded in the Shopify admin that answers
          questions about your store and can prepare actions (such as price or inventory changes)
          for your review. You remain responsible for reviewing and approving any action before it
          is executed — the app never executes a prepared action without explicit merchant
          approval.
        </p>
      </section>

      <section style={SECTION_STYLE}>
        <h2>AI-generated content</h2>
        <p>
          Responses, insights, and recommendations are generated by a third-party AI model and may
          be incomplete or inaccurate. You should verify anything important — pricing, inventory,
          and customer-facing decisions — before acting on it.
        </p>
      </section>

      <section style={SECTION_STYLE}>
        <h2>Your API keys</h2>
        <p>
          If you configure your own Anthropic or OpenAI API key in Settings, usage is billed by
          that provider directly to your account, subject to their pricing and terms. We are not
          responsible for charges incurred on your AI provider account.
        </p>
      </section>

      <section style={SECTION_STYLE}>
        <h2>Acceptable use</h2>
        <p>
          You agree not to use the app to violate Shopify&apos;s Acceptable Use Policy, applicable law,
          or the rights of your customers.
        </p>
      </section>

      <section style={SECTION_STYLE}>
        <h2>Termination</h2>
        <p>
          You may uninstall the app at any time from your Shopify admin. Upon uninstallation, your
          data is deleted per our <a href="/privacy">Privacy Policy</a>.
        </p>
      </section>

      <section style={SECTION_STYLE}>
        <h2>Changes</h2>
        <p>We may update these terms from time to time; continued use of the app after a change constitutes acceptance.</p>
      </section>
    </main>
  );
}
